plugins {
    id 'com.android.application'
}

def signingPropertiesFile = rootProject.file('keystore.properties')
def signingProperties = new Properties()
if (signingPropertiesFile.exists()) {
    signingPropertiesFile.withInputStream { signingProperties.load(it) }
}

android {
    namespace 'org.openquestcamera.app'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'org.openquestcamera.app'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '0.1'
    }

    signingConfigs {
        if (signingPropertiesFile.exists()) {
            release {
                storeFile rootProject.file(signingProperties['storeFile'])
                storePassword signingProperties['storePassword']
                keyAlias signingProperties['keyAlias']
                keyPassword signingProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (signingPropertiesFile.exists()) signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
